create table csp_report(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                        timestamp TIMESTAMP NOT NULL,
                        uri VARCHAR(255),
                        referrer VARCHAR(255),
                        blocked VARCHAR(255),
                        violated VARCHAR(255),
                        original_policy VARCHAR(255),
                        source VARCHAR(255),
                        sample VARCHAR(255),
                        line VARCHAR(255));
